### ISSUE TITLE
Run the code

### ISSUE THREAD

**Issue by Karansxa** [nicholascioli/clack#1]
Hello,
Can you help me with the installation and how to run the code for the first time.

**Comment by nicholascioli** [comment]
Sure.

Note: If you have an android device, then you can download a prebuilt apk from [the releases page](https://github.com/nicholascioli/clack/releases).

To build the app, first make sure that you have [installed flutter](https://flutter.dev/docs/get-started/install) and then do the following:

```bash
flutter pub get
flutter build
```

The built app can then be loaded directly onto your phone by running:

```bash
flutter install
```

I'll update the wiki to include usage and installation instructions.
