### ISSUE TITLE
Videos are broken

### ISSUE THREAD

**Issue by nicholascioli** [nicholascioli/clack#3]
TikTok is now enforcing a valid Referer on its video streams.

This would be an easy fix, but [adding headers is not supported by video_plugin](https://github.com/flutter/flutter/issues/16466). I'll have to see what other options are available.

**Comment by purelogiq** [comment]
@nicholascioli  is it possible to create a local HTTP server and route video requests through that? 

e.g.

```dart
void loopServer(HttpServer server) async {
    await for (HttpRequest request in server) {
      // Set headers in tiktok video request and passthrough url path/params to cdn host
      // Open video stream
      // Respond with video stream
    }
}


VideoPlayerController.network('http://127.0.0.1:$serverPort/tiktokvidpath?params')
```

Playing video through a local HTTP server works well on both iOS and Android. Just have to hook into the lifecycle methods to make sure the server hasn't been killed by the system when resuming the app.

I would provide a more thorough implementation but I'm still new with dart & flutter.

**Comment by nicholascioli** [comment]
Hmm, I don't know if I'd be able to intercept the native video_player's requests.

As a workaround for now, I've switched to [BetterPlayer](https://github.com/jhomlala/betterplayer) due to its support for both headers and list-optimized videos.

**Comment by rohitsharma1113** [comment]
@nicholascioli Is there a plugin where I can add a CloudFront cookie for accessing secure HLS stream ? 
BetterPlayer only seems to support headers which is not fulfilling my use case.
